"""empty message

Revision ID: 103e2ebc3b0e
Revises: 83b7efba1f87
Create Date: 2021-02-11 13:47:06.462880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '103e2ebc3b0e'
down_revision = '83b7efba1f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.drop_index('user_name', table_name='user')
    op.create_unique_constraint(None, 'user', ['name'])
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('user_name', 'user', ['user_name'], unique=True)
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
