"""empty message

Revision ID: 83b7efba1f87
Revises: 6d78ddaf9e3d
Create Date: 2021-02-11 13:39:44.854397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83b7efba1f87'
down_revision = '6d78ddaf9e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.String(length=120), nullable=False))
    op.drop_index('username', table_name='user')
    op.create_unique_constraint(None, 'user', ['user_name'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('username', 'user', ['username'], unique=True)
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###
